const messages = {
	INVALID_INPUT_PARAMETERS: 'INVALID_INPUT_PARAMETERS',
	ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
	ROLE_MUST_BE_MANAGER_ADMIN_OR_USER: 'ROLE_MUST_BE_MANAGER_ADMIN_OR_USER',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	UNRECOGNIZED_FIELD: 'UNRECOGNIZED_FIELD',
	UNAUTHORIZED: 'UNAUTHORIZED',
	ACESSES_DENIED: 'ACESSES_DENIED',
	TOKEN_IS_QUIRED: 'TOKEN_IS_QUIRED',
	MUST_BE_A_VALID_STRING: 'TOKEN_MUST_BE_A_VALID_STRING',
	INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',
	ID_IS_QUIRED: 'ID_IS_QUIRED',
} as const;
export { messages };

export function formatExpectedTypeMismatch(
	expected: string,
	received: string,
): string {
	return `EXPECTED_${expected.toUpperCase()}_RECEIVED_${received.toUpperCase()}`;
}
