const messages = {
	PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
	PASSWORD_NO_NUMBER: 'PASSWORD_NO_NUMBER',
	PASSWORD_NO_UPPERCASE: 'PASSWORD_NO_UPPERCASE',
	PASSWORD_NO_SPECIAL_CHAR: 'PASSWORD_NO_SPECIAL_CHAR',
	INVALID_UUID_FORMAT: 'INVALID_UUID_FORMAT',
	INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
	INVALID_NAME_FORMAT: 'INVALID_NAME_FORMAT',
	INVALID_ROLE_NAME: 'INVALID_ROLE_NAME',
	INVALID_PHONE_FORMAT: 'INVALID_PHONE_FORMAT',
	INVALID_URL_FORMAT: 'INVALID_URL_FORMAT',
	ROLE_MANAGER_PERMISSION_REQUIRED: 'ROLE_MANAGER_PERMISSION_REQUIRED',
} as const;
export { messages };

// export function formatExpectedTypeMismatch(
// 	expected: string,
// 	received: string,
// ): string {
// 	return `EXPECTED_${expected.toUpperCase()}_RECEIVED_${received.toUpperCase()}`;
// }
