const errorMessage = {
	EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
	ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
	INVALID_PARAMS: 'INVALID_PARAMS',
	NAME_MUST_BE_A_STRING: 'NAME_MUST_BE_A_STRING',
	NAME_IS_REQUIRED: 'NAME_IS_REQUIRED',
	EMAIL_MUST_BE_A_STRING: 'EMAIL_MUST_BE_A_STRING',
	EMAIL_IS_REQUIRED: 'EMAIL_IS_REQUIRED',
	PASSWORD_MUST_BE_A_STRING: 'PASSWORD_MUST_BE_A_STRING',
	PASSWORD_IS_REQUIRED: 'PASSWORD_IS_REQUIRED',
	ROLE_MUST_BE_A_STRING: 'ROLE_MUST_BE_A_STRING',
	INVALID_ROLE: 'INVALID_ROLE',
	ROLE_IS_REQUIRED: 'ROLE_IS_REQUIRED',
	INVALID_EMAIL: 'INVALID_EMAIL',
	PASSWORD_MUST_HAVE_AT_LEAST_EIGHT_CHARACTERS:
		'PASSWORD_MUST_HAVE_AT_LEAST_EIGHT_CHARACTERS',
	PASSWORD_MUST_HAVE_AT_LEAST_ONE_NUMBER:
		'PASSWORD_MUST_HAVE_AT_LEAST_ONE_NUMBER',
	PASSWORD_MUST_HAVE_AT_LEAST_ONE_CAPITAL_LETTER:
		'PASSWORD_MUST_HAVE_AT_LEAST_ONE_CAPITAL_LETTER',
	PASSWORD_MUST_HAVE_AT_LEAST_ONE_SPECIAL_LETTER:
		'PASSWORD_MUST_HAVE_AT_LEAST_ONE_SPECIAL_LETTER',
} as const;
export { errorMessage };
