export const validatorMessage = {
	NAME_MUST_BE_A_STRING: 'NAME_MUST_BE_A_STRING',
	NAME_IS_REQUIRED: 'NAME_IS_REQUIRED',
	EMAIL_MUST_BE_A_STRING: 'EMAIL_MUST_BE_A_STRING',
	EMAIL_IS_REQUIRED: 'EMAIL_IS_REQUIRED',
	PASSWORD_MUST_BE_A_STRING: 'PASSWORD_MUST_BE_A_STRING',
	PASSWORD_IS_REQUIRED: 'PASSWORD_IS_REQUIRED',
	ROLE_MUST_BE_A_STRING: 'ROLE_MUST_BE_A_STRING',
	INVALID_ROLE: 'INVALID_ROLE',
	ROLE_IS_REQUIRED: 'ROLE_IS_REQUIRED',
};
